### PR TITLE
feat: add maximum retries to `RepeatGoalStructure`

### PR DESCRIPTION
**Pull request by Laura-Berkers**
## Description

This PR adds a new optional parameter to the `RepeatGoalStructure` class. The class now keeps track of the amount of times it has retried, and if the maximum amount of retires is reached, the repeat goal structure fails. If the user does not specify a maximum amount of retries, the goal structure will keep retrying infinitly, just like the existing behaviour.

## Checklist
- [x] Set the proper pull request name
- [x] Merged dev into your branch

### CODE REVIEW

**Comment by JensSteenmetz** [comment]
Could you rename the PR to

feat: add maximum retries to `RepeatGoalStructure`

**Review by JensSteenmetz — DISMISSED** [review]
LGTM!

**Review by JensSteenmetz — DISMISSED** [review]
LGTM!

**Review by Tboefijn — DISMISSED** [review]
Ik zag 2 resharper comments staan maar volgens mij maakt het niet veel uit dat die erin zitten. LGTM!

**Review by Tboefijn — APPROVED** [review]
LGTM!

**Review by JensSteenmetz — APPROVED** [review]
LGTM!

**Pull request merged**
